# Regiment

In [1]:
import pandas as pd
import numpy as np

### Step 2. Create the DataFrame with the following values:

In [2]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'], 
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'], 
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'], 
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}

### Step 3. Assign it to a variable called regiment.
#### Don't forget to name each column

In [3]:
regiment=pd.DataFrame(raw_data, columns=["regiment","company","name","preTestScore", "postTestScore"])
regiment.head()

     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
4    Dragoons     1st     Cooze             3             70

      regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

### Step 4. What is the mean preTestScore from the regiment Nighthawks?

In [5]:
regiment[regiment["regiment"]=="Nighthawks"]["preTestScore"].mean()

np.float64(15.25)

15.25

regiment
Nighthawks    15.25
Name: preTestScore, dtype: float64


### Step 5. Present general statistics by company

In [6]:
regiment.groupby("company").describe()

        preTestScore                                                      \
               count       mean        std  min   25%   50%    75%   max
company
1st              6.0   6.666667   8.524475  2.0  3.00   3.5   4.00  24.0
2nd              6.0  15.500000  14.652645  2.0  2.25  13.5  29.25  31.0

        postTestScore
                count       mean        std   min    25%   50%   75%   max
company
1st               6.0  57.666667  27.485754  25.0  34.25  66.0  70.0  94.0
2nd               6.0  67.000000  14.057027  57.0  58.25  62.0  68.0  94.0

count      12
unique      2
top       1st
freq        6
Name: company, dtype: object

### Step 6. What is the mean of each company's preTestScore?

In [8]:
regiment.groupby("company")["preTestScore"].mean()

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

company
1st     6.666667
2nd    15.500000
Name: preTestScore, dtype: float64

### Step 7. Present the mean preTestScores grouped by regiment and company

In [9]:
regiment.groupby(["regiment","company"])["preTestScore"].mean()

regiment    company
Dragoons    1st         3.5
            2nd        27.5
Nighthawks  1st        14.0
            2nd        16.5
Scouts      1st         2.5
            2nd         2.5
Name: preTestScore, dtype: float64

regiment    company
Dragoons    1st         3.5
            2nd        27.5
Nighthawks  1st        14.0
            2nd        16.5
Scouts      1st         2.5
            2nd         2.5
Name: preTestScore, dtype: float64

### Step 8. Present the mean preTestScores grouped by regiment and company without heirarchical indexing

In [13]:
regiment.groupby(["regiment","company"])["preTestScore"].mean().reset_index()

     regiment company  preTestScore
0    Dragoons     1st           3.5
1    Dragoons     2nd          27.5
2  Nighthawks     1st          14.0
3  Nighthawks     2nd          16.5
4      Scouts     1st           2.5
5      Scouts     2nd           2.5

     regiment company  preTestScore
0    Dragoons     1st           3.5
1    Dragoons     2nd          27.5
2  Nighthawks     1st          14.0
3  Nighthawks     2nd          16.5
4      Scouts     1st           2.5
5      Scouts     2nd           2.5

### Step 9. Group the entire dataframe by regiment and company

In [15]:
regiment.groupby(["regiment","company"]).describe()

                   preTestScore                                             \
                          count  mean        std   min    25%   50%    75%
regiment   company
Dragoons   1st              2.0   3.5   0.707107   3.0   3.25   3.5   3.75
           2nd              2.0  27.5   4.949747  24.0  25.75  27.5  29.25
Nighthawks 1st              2.0  14.0  14.142136   4.0   9.00  14.0  19.00
           2nd              2.0  16.5  20.506097   2.0   9.25  16.5  23.75
Scouts     1st              2.0   2.5   0.707107   2.0   2.25   2.5   2.75
           2nd              2.0   2.5   0.707107   2.0   2.25   2.5   2.75

                         postTestScore                                      \
                     max         count  mean        std   min    25%   50%
regiment   company
Dragoons   1st       4.0           2.0  47.5  31.819805  25.0  36.25  47.5
           2nd      31.0           2.0  75.5  26.162951  57.0  66.25  75.5
Nighthawks 1st      24.0           2.0  59.5  48.790368  25.0  42.25  59.5
           2nd      31.0           2.0  59.5   3.535534  57.0  58.25  59.5
Scouts     1st       3.0           2.0  66.0   5.656854  62.0  64.00  66.0
           2nd       3.0           2.0  66.0   5.656854  62.0  64.00  66.0


                      75%   max
regiment   company
Dragoons   1st      58.75  70.0
           2nd      84.75  94.0
Nighthawks 1st      76.75  94.0
           2nd      60.75  62.0
Scouts     1st      68.00  70.0
           2nd      68.00  70.0

                   preTestScore                                             \
                          count  mean        std   min    25%   50%    75%
regiment   company
Dragoons   1st              2.0   3.5   0.707107   3.0   3.25   3.5   3.75
           2nd              2.0  27.5   4.949747  24.0  25.75  27.5  29.25
Nighthawks 1st              2.0  14.0  14.142136   4.0   9.00  14.0  19.00
           2nd              2.0  16.5  20.506097   2.0   9.25  16.5  23.75
Scouts     1st              2.0   2.5   0.707107   2.0   2.25   2.5   2.75
           2nd              2.0   2.5   0.707107   2.0   2.25   2.5   2.75

                         postTestScore                                      \
                     max         count  mean        std   min    25%   50%
regiment   company
Dragoons   1st       4.0           2.0  47.5  31.819805  25.0  36.25  47.5
           2nd      31.0           2.0  75.5  26.162951  57.0  66.25  75.5
Nighthawks 1st      24.0           2.0  59.5  48.790368  25.0  42.25  59.5
           2nd      31.0           2.0  59.5   3.535534  57.0  58.25  59.5
Scouts     1st       3.0           2.0  66.0   5.656854  62.0  64.00  66.0
           2nd       3.0           2.0  66.0   5.656854  62.0  64.00  66.0


                      75%   max
regiment   company
Dragoons   1st      58.75  70.0
           2nd      84.75  94.0
Nighthawks 1st      76.75  94.0
           2nd      60.75  62.0
Scouts     1st      68.00  70.0
           2nd      68.00  70.0

### Step 10. What is the number of observations in each regiment and company

In [ ]:
# Count cuenta, para cada pareja (regimiento, compañía), 
# los valores no nulos de cada una de las demás columnas, lo que viene a ser observaciones
regiment.groupby(["regiment","company"]).count()

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
dtype: int64

In [19]:
# size() cuenta filas y da un único número por grupo, mejor que count ya que no cuenta los nan
regiment.groupby(["regiment","company"]).size()

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
dtype: int64

In [ ]:
# Cuenta cuántas filas idénticas hay dentro de cada par regiment company,
#  devolviendo una serie al final con ese conteo
regiment.groupby(["regiment","company"]).value_counts()

regiment    company  name      preTestScore  postTestScore
Dragoons    1st      Cooze     3             70               1
                     Jacon     4             25               1
            2nd      Ryaner    24            94               1
                     Sone      31            57               1
Nighthawks  1st      Miller    4             25               1
                     Jacobson  24            94               1
            2nd      Ali       31            57               1
                     Milner    2             62               1
Scouts      1st      Sloan     2             62               1
                     Piger     3             70               1
            2nd      Riani     2             62               1
                     Ali       3             70               1
Name: count, dtype: int64

regiment    company
Dragoons    1st        2
            2nd        2
Nighthawks  1st        2
            2nd        2
Scouts      1st        2
            2nd        2
Name: name, dtype: int64

### Step 11. Iterate over a group and print the name and the whole data from the regiment

In [22]:
regiment.groupby('regiment').describe()

           preTestScore                                                  \
                  count   mean        std  min   25%   50%    75%   max
regiment
Dragoons            4.0  15.50  14.153916  3.0  3.75  14.0  25.75  31.0
Nighthawks          4.0  15.25  14.453950  2.0  3.50  14.0  25.75  31.0
Scouts              4.0   2.50   0.577350  2.0  2.00   2.5   3.00   3.0

           postTestScore
                   count  mean        std   min   25%   50%   75%   max
regiment
Dragoons             4.0  61.5  28.757608  25.0  49.0  63.5  76.0  94.0
Nighthawks           4.0  59.5  28.242993  25.0  49.0  59.5  70.0  94.0
Scouts               4.0  66.0   4.618802  62.0  62.0  66.0  70.0  70.0

In [24]:
# name es el indice nuevo, group es el df restante
for name, group in regiment.groupby('regiment'):
    print(name)
    print(group)
    print("-----")

Dragoons
   regiment company    name  preTestScore  postTestScore
4  Dragoons     1st   Cooze             3             70
5  Dragoons     1st   Jacon             4             25
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
-----
Nighthawks
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
-----
Scouts
   regiment company   name  preTestScore  postTestScore
8    Scouts     1st  Sloan             2             62
9    Scouts     1st  Piger             3             70
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70
-----

Dragoons
----
   regiment company    name  preTestScore  postTestScore
4  Dragoons     1st   Cooze             3             70
5  Dragoons     1st   Jacon             4             25
6  Dragoons     2nd  Ryaner            24             94
7  Dragoons     2nd    Sone            31             57
Nighthawks
----
     regiment company      name  preTestScore  postTestScore
0  Nighthawks     1st    Miller             4             25
1  Nighthawks     1st  Jacobson            24             94
2  Nighthawks     2nd       Ali            31             57
3  Nighthawks     2nd    Milner             2             62
Scouts
----
   regiment company   name  preTestScore  postTestScore
8    Scouts     1st  Sloan             2             62
9    Scouts     1st  Piger             3             70
10   Scouts     2nd  Riani             2             62
11   Scouts     2nd    Ali             3             70